title: FAQ
default_lang: pt-br
author:
  name: 'Angelo Dias'
  email: angelo@angelodias.com.br
taxonomies:
  - category
  - tag
metadata:
  description: 'Perguntas frequentes sobre Angelo Dias'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
